### ISSUE TITLE
Document

### ISSUE THREAD

**Issue by ltfred** [loki-os/go-ethernet-ip#6]
Are there any documentation or examples? I run ‘ListIdentity’, no item return.

**Comment by TheFern2** [comment]
Is hard to dissect from source code if you install the go-cip it pulls this repo as a dependency but is using an old commit from this repo. Not the latest repo code which is using an entire different structure.

Reading through this code, I can't figure out how to do anything meaningful other than reading all tags with a NewController... object.

I also tried to use goplc repo and that one I couldn't even connect to the plc.

Side note: I am working on porting pylogix to go because I can't find anything reliable in go.

**Comment by TheFern2** [comment]
Have a look at this wrapper for libplctag I am working on. Latest stable version is v0.0.4, and beta v0.0.3-beta6


https://github.com/libplctag/goplctag

**Comment by MiguelValentine** [comment]
I add some example.
Maybe can help u.
